services:
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    image: nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=home.enunpimpam.com, www.home.enunpimpam.com

  web2:
    image: nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - ./eric:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=eric.enunpimpam.com, www.eric.enunpimpam.com
